config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :followers, only: [:index, :create]
  resources :polls, :users
  resources :votes, only: [:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "polls#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
  # has_many :users
  # belongs_to :user
end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :user

  has_many :votes
  has_many :users, through: :votes



end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :votes
  has_many :polls, through: :votes
  has_many :polls

  def followers
    Follower.where("followed_id = #{id}")
  end

  def following
    Follower.where("follower_id = #{id}")
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :poll
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index

  end
  def create
    Follower.create(followed_id: params[:followed_id].to_i, follower_id: params[:user_id].to_i)
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.all
  end

  def show
    @poll = Poll.find(params[:id])
  end

  def new
    @poll = Poll.new
  end

  def create
    @poll = Poll.create(poll_params)
    creating_user = User.find_by(username: current_user.username)
    current_score = creating_user.score
    if creating_user.user_type == 'free'
      creating_user.update(score: (current_score - 10))
    end
    redirect_to @poll
  end

  private

  def poll_params
    params.require(:poll).permit(:user_id, :question, :answer_one, :answer_two)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
   @users = User.all
 end

 def show
   @user = User.find(params[:id])
 end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    voting_user = User.find_by(username: current_user.username)
    @vote = Vote.create(user_id: voting_user.id, poll_id: params[:poll_id].to_i, vote: params[:button])

    voted_on_poll_id = params[:poll_id].to_i
    poll_user_id = Poll.find(voted_on_poll_id).user_id
    poll_creator = User.find_by(id: poll_user_id)

    voter_current_score = voting_user.score
    creator_current_score = poll_creator.score

    voting_user.update(score: (voter_current_score + 2))
    poll_creator.update(score: (creator_current_score + 1))

    redirect_to polls_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/followers/index.html.erb
<div class="box">
  <% @user = User.find(current_user.id) %>

  <div class="box">
    Followers:
    <br>
    <% @user.followers.each do |f| %>
      <%= link_to User.find(f.follower_id).username, user_path(@user) %><br>
    <% end %>
  </div>

  <div class="box">
    Following:
    <br>
    <% @user.following.each do |f| %>
      <%= link_to User.find(f.followed_id).username, user_path(@user) %><br>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iVote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation" style="margin-bottom:1px;">
      <div class="navbar-brand">
        <a class="navbar-item" href="<%= root_path %>">iVote</a>
      </div>

    <% if user_signed_in? %>
      <div class="navbar-menu">
        <a class="navbar-item" href="<%= new_poll_path %>">New Poll</a>
        <a class="navbar-item" href="<%= users_path %>">Users</a>



    <nav class="navbar" role="navigation" aria-label="dropdown navigation">
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          <%= current_user.username %>
        </a>

        <div class="navbar-dropdown is-right">
          <a class="navbar-item" href="<%= user_path(current_user) %>">Profile</a>
          <a class="navbar-item" href="<%= edit_user_registration_path(current_user.name) %>">Edit Profile</a>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class:'navbar-item' %>
          <hr class="navbar-divider">
          <div class="navbar-item">
            Score: <%= current_user.score %>
          </div>
        </div>

  </div>
</div>
</div>

      </div>
    <% else %>
      <div class="navbar-menu">
        <a class="navbar-item" href="<%= new_user_session_path %>">Sign In</a>
        <a class="navbar-item" href="<%= new_user_registration_path %>">Sign Up</a>
      </div>
    <% end %>

  </nav>


    <%= yield %>
  </body>

  <footer class="footer">
      <div class="content has-text-left">
        <p>
          <strong>iVote©</strong> by Kai & Fez.
        </p>
      </div>
  </footer>
</html>

app/views/polls/index.html.erb
<% @user = User.find(current_user.id) %>

<div class="container is-fluid" style="margin-top:20px; margin-bottom:20px;">
  <% @polls.reverse.each do |poll| %>
    <div class="box is-centered" style="text-align: center;">
      <h1 style="font-size:2em"><%= poll.question %></h1><br>
      <h2 style="font-size:1.5em">

        <% if Vote.all.where(poll_id: poll.id).count > 0 %>
          <% red = (((Vote.all.where(poll_id: poll.id, vote: true).count).to_f/(Vote.all.where(poll_id: poll.id).count).to_f)*100).round %>
          <% green = 100-red%>
        <% end %>

        <%= form_tag(votes_path) %>

        <%= hidden_field_tag 'poll_id', "#{poll.id}" %>

        <% if !@user.votes.find_by(poll_id: poll.id) %>
          <%= button_tag(type: 'submit', class: "button is-danger", value: true) do %>
          <% content_tag(:strong, poll.answer_one) %><% end %>
          or
          <%= button_tag(type: 'submit', class: "button is-success", value: false) do %>
          <% content_tag(:strong, poll.answer_two) %><% end %>
        <% else %>
          You voted for <b><u><%= @user.votes.find_by(poll_id: poll.id).vote ? poll.answer_one : poll.answer_two %></u></b> <br><br>
          <%= button_tag(type: 'button', class: "button is-danger", value: true) do %>
          <% content_tag(:strong, poll.answer_one) %><% end %>
          or
          <%= button_tag(type: 'button', class: "button is-success", value: false) do %>
          <% content_tag(:strong, poll.answer_two) %><% end %>

          <br><br>

          <div class="vote-bar" style="width:<%= red %>%; background-color:#ff3860; border-top-right-radius:0px; border-bottom-right-radius:0px"></div>
          <div class="vote-bar" style="width:<%= green %>%; background-color:#23d160; border-top-left-radius:0px; border-bottom-left-radius:0px;"></div>

          <%= red %>% - <%= green %>%
          <br><br>
          Total Votes
          <br>
          <%= poll.votes.where(vote: true).count %>  -  <%=  poll.votes.where(vote: false).count%>
        <% end %>

      </form>

    </h2><br>





    <h5 style="font-size:0.8em">Created by:
      <%= link_to poll.user.username, user_path(poll.user.id) %></h5>
  </div>
<% end %>

</div>

app/views/polls/new.html.erb
<% @user = User.find(current_user.id) %>

  <% if @user.user_type == "free" && @user.score < 5 %>

    <p>You need a minimum of 5 points to create a poll. Answer
      <%="#{5-@user.score}"%>
      more polls to get enough points!</p>

  <% else%>
    <div class="section">
      <div class="container">
        <div class="columns is-centered">
          <div class="column is-4">
            <h2 class="title is-2">Create New Poll</h2>
            <%= form_for @poll do |f| %>
            <%= f.label :question %>
            <%= f.text_field :question %><br>
            <%= f.label :answer_one %>
            <%= f.text_field :answer_one %><br>
            <%= f.label :answer_two %>
            <%= f.text_field :answer_two %><br>
            <%= f.hidden_field :user_id, :value => @user.id %><br>

            <%= f.submit %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/polls/show.html.erb
<div class="box is-centered" style="text-align: center;">
  <h1 style="font-size:2em"><%= @poll.question %></h1><br>
  <h2 style="font-size:1.5em">

    <%= form_tag(votes_path) %>

    <%= hidden_field_tag 'poll_id', "#{@poll.id}" %>

    <%= button_tag(type: 'submit', class: "button is-danger", value: true, action: "poll_path(@poll)") do %>
    <% content_tag(:strong, @poll.answer_one) %><% end %>
    or
    <%= button_tag(type: 'submit', class: "button is-success", value: false, action: poll_path(@poll)) do %>
    <% content_tag(:strong, @poll.answer_two) %><% end %>

  </form>

</h2><br>
<% if Vote.all.where(poll_id: @poll.id).count > 0 %>
  <%= green = (((Vote.all.where(poll_id: @poll.id, vote: true).count).to_f/(Vote.all.where(poll_id: @poll.id).count).to_f)*100).round %>%
  <%= red = 100-green%>
<% end %>

<h5 style="font-size:0.8em">Created by:
  <%= link_to @poll.user.username, user_path(@poll.user.id) %></h5>
</div>

</div>

app/views/users/index.html.erb
<% counter = 0 %>
  <div class="box">
    <h1 class="title is-1">Leaderboards</h1>
    <br>

    <% @users.order(score: :desc).each do |user| %>
      <div class="box">
        <ol>
          <%=counter += 1%>.
          <%= link_to user.name, user_path(user) %>
          <% if user.user_type != "free" %>
            ✔️<% end %>
          <br>
          Score:
          <%= user.score %>
          <br>
          <a class="button is-right is-info is-hovered">Follow</a>
        </ol>
      </div>
      <br>
    <% end %>
  </div>

app/views/users/show.html.erb
<div class="container is-fluid" style="margin-top:20px; margin-bottom:20px;">
  <div class="box">
    @<%= @user.username %>
    <% if @user.user_type != "free" %>
      ✔️<% end %>
    <br>
    <%= @user.name %>
    <br>

    <% logged_in_user = User.find(current_user.id) %>

    <% if !logged_in_user.following.include?(@user.id) %>
    <%= form_tag(followers_path) %>
      <%= hidden_field_tag 'user_id', "#{current_user.id}" %>
      <%= hidden_field_tag 'followed_id', "#{params[:id]}" %>
      <%= button_tag(type: 'submit', class: "button is-info") do %>
        <% content_tag(:strong, 'Follow') %>
      <% end %>
    </form>
    <% end %>
  </div>

  <% @user.polls.reverse.each do |poll| %>
    <div class="box is-centered" style="text-align: center;">
      <h1 style="font-size:2em"><%= poll.question %></h1><br>

      <h2 style="font-size:1.5em">

        <%= form_tag(votes_path) %>

        <%= hidden_field_tag 'poll_id', "#{poll.id}" %>

        <%= button_tag(type: 'submit', class: "button is-danger", value: true) do %>
        <% content_tag(:strong, poll.answer_one) %><% end %>
        or
        <%= button_tag(type: 'submit', class: "button is-success", value: false) do %>
        <% content_tag(:strong, poll.answer_two) %><% end %>

        </form>
        
    </h2><br>
    <% if Vote.all.where(poll_id: poll.id).count > 0 %>
      <%= green = (((Vote.all.where(poll_id: poll.id, vote: true).count).to_f/(Vote.all.where(poll_id: poll.id).count).to_f)*100).round %>%
      <%= red = 100-green%>%
    <% end %>

    <h5 style="font-size:0.8em">Created by:
      <%= link_to poll.user.username, user_path(poll.user.id) %></h5>
  </div>
<% end %>

</div>